packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  core-js: false
  esbuild: true
  prisma: true
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
